// Code generated by Slice Machine. DO NOT EDIT.

import AlternateGrid from './AlternateGrid/index.svelte';
import BlogPost from './BlogPost/index.svelte';
import CardListView from './CardListView/index.svelte';

export const components = {
	alternate_grid: AlternateGrid,
	blog_post: BlogPost,
	card_list_view: CardListView
};
