// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice = AboutSlice;

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
	/**
	 * Slice Zone field in *About Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
	 * Meta Title field in *About Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: about_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *About Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: about_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<AboutPageDocumentData>,
	'about_page',
	Lang
>;

type BlogListDocumentDataSlicesSlice = PostlistSlice;

/**
 * Content for Blog List documents
 */
interface BlogListDocumentData {
	/**
	 * Title field in *Blog List*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Blog page title
	 * - **API ID Path**: blog_list.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Description field in *Blog List*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Blog page description
	 * - **API ID Path**: blog_list.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Slice zone field in *Blog List*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_list.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogListDocumentDataSlicesSlice>;
}

/**
 * Blog List document from Prismic
 *
 * - **API ID**: `blog_list`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogListDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<BlogListDocumentData>,
	'blog_list',
	Lang
>;

type BlogPostDocumentDataSlicesSlice = PostcontentSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Blog post title
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Date field in *Blog Post*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Publication date
	 * - **API ID Path**: blog_post.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Author field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Author name
	 * - **API ID Path**: blog_post.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	author: prismic.KeyTextField;

	/**
	 * Featured Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField<never>;

	/**
	 * Excerpt field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Short excerpt for blog list view
	 * - **API ID Path**: blog_post.excerpt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	excerpt: prismic.RichTextField;

	/**
	 * Slice zone field in *Blog Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostDocumentData>,
	'blog_post',
	Lang
>;

type CaseStudiesListDocumentDataSlicesSlice = PostlistSlice;

/**
 * Content for Case Studies List documents
 */
interface CaseStudiesListDocumentData {
	/**
	 * Title field in *Case Studies List*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Case Studies page title
	 * - **API ID Path**: case_studies_list.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Description field in *Case Studies List*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Case Studies page description
	 * - **API ID Path**: case_studies_list.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Slice zone field in *Case Studies List*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_studies_list.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CaseStudiesListDocumentDataSlicesSlice>;
}

/**
 * Case Studies List document from Prismic
 *
 * - **API ID**: `case_studies_list`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudiesListDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<CaseStudiesListDocumentData>,
		'case_studies_list',
		Lang
	>;

type CaseStudyDocumentDataSlicesSlice = PostcontentSlice;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
	/**
	 * Title field in *Case Study*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Case study title
	 * - **API ID Path**: case_study.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Date field in *Case Study*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Publication date
	 * - **API ID Path**: case_study.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Client field in *Case Study*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Client name
	 * - **API ID Path**: case_study.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	client: prismic.KeyTextField;

	/**
	 * Featured Image field in *Case Study*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.featured_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField<never>;

	/**
	 * Excerpt field in *Case Study*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Short excerpt for case study list view
	 * - **API ID Path**: case_study.excerpt
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	excerpt: prismic.RichTextField;

	/**
	 * Slice zone field in *Case Study*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice>;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CaseStudyDocumentData>,
	'case_study',
	Lang
>;

type ContactsliceDocumentDataSlicesSlice = ContactSliceSlice;

/**
 * Content for ContactSlice documents
 */
interface ContactsliceDocumentData {
	/**
	 * Slice Zone field in *ContactSlice*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contactslice.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ContactsliceDocumentDataSlicesSlice> /**
	 * Meta Title field in *ContactSlice*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: contactslice.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *ContactSlice*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: contactslice.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *ContactSlice*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contactslice.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * ContactSlice document from Prismic
 *
 * - **API ID**: `contactslice`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactsliceDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ContactsliceDocumentData>,
	'contactslice',
	Lang
>;

type HomepageDocumentDataSlicesSlice = AlternateGridSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *HomePage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *HomePage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *HomePage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *HomePage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

type PrivacyPolicyDocumentDataSlicesSlice = LegalPageSlice;

/**
 * Content for PrivacyPolicy documents
 */
interface PrivacyPolicyDocumentData {
	/**
	 * Slice Zone field in *PrivacyPolicy*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: privacy_policy.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice> /**
	 * Meta Title field in *PrivacyPolicy*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: privacy_policy.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *PrivacyPolicy*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: privacy_policy.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *PrivacyPolicy*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: privacy_policy.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * PrivacyPolicy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<PrivacyPolicyDocumentData>,
	'privacy_policy',
	Lang
>;

type ServicesDocumentDataSlicesSlice = ServicesSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
	/**
	 * Slice Zone field in *Services*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
	 * Meta Title field in *Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: services.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Services*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: services.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Services*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<ServicesDocumentData>,
	'services',
	Lang
>;

export type AllDocumentTypes =
	| AboutPageDocument
	| BlogListDocument
	| BlogPostDocument
	| CaseStudiesListDocument
	| CaseStudyDocument
	| ContactsliceDocument
	| HomepageDocument
	| PrivacyPolicyDocument
	| ServicesDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
	/**
	 * Title field in *About → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the main title
	 * - **API ID Path**: about.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Subtitle field in *About → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter the subtitle
	 * - **API ID Path**: about.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField;

	/**
	 * Content field in *About → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter the main content
	 * - **API ID Path**: about.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;

	/**
	 * Logo field in *About → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.default.primary.logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * CTA Title field in *About → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the CTA title
	 * - **API ID Path**: about.default.primary.cta_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cta_title: prismic.TitleField;

	/**
	 * CTA Description field in *About → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter the CTA description
	 * - **API ID Path**: about.default.primary.cta_description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cta_description: prismic.RichTextField;

	/**
	 * CTA Button Text field in *About → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter the CTA button text
	 * - **API ID Path**: about.default.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_button_text: prismic.KeyTextField;

	/**
	 * CTA Button Link field in *About → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Enter the CTA button link
	 * - **API ID Path**: about.default.primary.cta_button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_button_link: prismic.LinkField;
}

/**
 * Primary content in *About → Items*
 */
export interface AboutSliceDefaultItem {
	/**
	 * Employee Name field in *About → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter employee name
	 * - **API ID Path**: about.items[].employee_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	employee_name: prismic.KeyTextField;

	/**
	 * Employee Position field in *About → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter employee position
	 * - **API ID Path**: about.items[].employee_position
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	employee_position: prismic.KeyTextField;

	/**
	 * Employee Image field in *About → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.items[].employee_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	employee_image: prismic.ImageField<never>;

	/**
	 * Employee Introduction field in *About → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter a brief introduction for the employee
	 * - **API ID Path**: about.items[].employee_intro
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	employee_intro: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutSliceDefaultPrimary>,
	Simplify<AboutSliceDefaultItem>
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About section for Kalvex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<'about', AboutSliceVariation>;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
	/**
	 * title field in *AlternateGrid → Default → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Default → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
	/**
	 * title field in *AlternateGrid → Image Right → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Image Right → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
	/**
	 * eyebrowHeadline field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrowHeadline: prismic.KeyTextField;

	/**
	 * title field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * image field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * items field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AlternateGridSliceDefaultPrimaryItemsItem>>;

	/**
	 * Main Content field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Content Goes Here
	 * - **API ID Path**: alternate_grid.default.primary.main_content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	main_content: prismic.RichTextField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AlternateGridSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
	/**
	 * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrowHeadline: prismic.KeyTextField;

	/**
	 * title field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * image field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * items field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AlternateGridSliceImageRightPrimaryItemsItem>>;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
	'imageRight',
	Simplify<AlternateGridSliceImageRightPrimary>,
	never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation = AlternateGridSliceDefault | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<'alternate_grid', AlternateGridSliceVariation>;

/**
 * Primary content in *ContactSlice → Default → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
	/**
	 * Title field in *ContactSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Description field in *ContactSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactSliceSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault;

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSlice = prismic.SharedSlice<'contact_slice', ContactSliceSliceVariation>;

/**
 * Primary content in *LegalPage → Default → Primary*
 */
export interface LegalPageSliceDefaultPrimary {
	/**
	 * legal text field in *LegalPage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: legal_page.default.primary.legal_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	legal_text: prismic.RichTextField;
}

/**
 * Default variation for LegalPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalPageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LegalPageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LegalPage*
 */
type LegalPageSliceVariation = LegalPageSliceDefault;

/**
 * LegalPage Shared Slice
 *
 * - **API ID**: `legal_page`
 * - **Description**: LegalPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalPageSlice = prismic.SharedSlice<'legal_page', LegalPageSliceVariation>;

/**
 * Primary content in *PostContent → Default → Primary*
 */
export interface PostcontentSliceDefaultPrimary {
	/**
	 * Title field in *PostContent → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the post title
	 * - **API ID Path**: postcontent.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Date field in *PostContent → Default → Primary*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Select the post date
	 * - **API ID Path**: postcontent.default.primary.date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Author field in *PostContent → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter the author's name
	 * - **API ID Path**: postcontent.default.primary.author
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	author: prismic.KeyTextField;

	/**
	 * Featured Image field in *PostContent → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: postcontent.default.primary.featured_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	featured_image: prismic.ImageField<never>;

	/**
	 * Content field in *PostContent → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter the post content
	 * - **API ID Path**: postcontent.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for PostContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostcontentSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PostcontentSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PostContent*
 */
type PostcontentSliceVariation = PostcontentSliceDefault;

/**
 * PostContent Shared Slice
 *
 * - **API ID**: `postcontent`
 * - **Description**: Displays individual post content (blog post or case study)
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostcontentSlice = prismic.SharedSlice<'postcontent', PostcontentSliceVariation>;

/**
 * Primary content in *PostList → Default → Primary*
 */
export interface PostlistSliceDefaultPrimary {
	/**
	 * Title field in *PostList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the section title
	 * - **API ID Path**: postlist.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Description field in *PostList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter a brief description
	 * - **API ID Path**: postlist.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *PostList → Items*
 */
export interface PostlistSliceDefaultItem {
	/**
	 * Post Title field in *PostList → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the post title
	 * - **API ID Path**: postlist.items[].post_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	post_title: prismic.TitleField;

	/**
	 * Post Excerpt field in *PostList → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter a brief excerpt
	 * - **API ID Path**: postlist.items[].post_excerpt
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	post_excerpt: prismic.RichTextField;

	/**
	 * Post Date field in *PostList → Items*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Select the post date
	 * - **API ID Path**: postlist.items[].post_date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	post_date: prismic.DateField;

	/**
	 * Post Image field in *PostList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: postlist.items[].post_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	post_image: prismic.ImageField<never>;

	/**
	 * Post Link field in *PostList → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select the post link
	 * - **API ID Path**: postlist.items[].post_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	post_link: prismic.LinkField;
}

/**
 * Default variation for PostList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostlistSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PostlistSliceDefaultPrimary>,
	Simplify<PostlistSliceDefaultItem>
>;

/**
 * Slice variation for *PostList*
 */
type PostlistSliceVariation = PostlistSliceDefault;

/**
 * PostList Shared Slice
 *
 * - **API ID**: `postlist`
 * - **Description**: Displays a list of posts (blog posts or case studies)
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostlistSlice = prismic.SharedSlice<'postlist', PostlistSliceVariation>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
	/**
	 * Title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the main title for the services section
	 * - **API ID Path**: services.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter a brief description of the services offered
	 * - **API ID Path**: services.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * CTA Title field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Enter the CTA title
	 * - **API ID Path**: services.default.primary.cta_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cta_title: prismic.TitleField;

	/**
	 * CTA Description field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter the CTA description
	 * - **API ID Path**: services.default.primary.cta_description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	cta_description: prismic.RichTextField;

	/**
	 * CTA Link field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select a link for the CTA button
	 * - **API ID Path**: services.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Button Text field in *Services → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter the text for the CTA button
	 * - **API ID Path**: services.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
	/**
	 * Service Name field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter the name of the service
	 * - **API ID Path**: services.items[].service_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	service_name: prismic.KeyTextField;

	/**
	 * Service Icon field in *Services → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: services.items[].service_icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	service_icon: prismic.ImageField<never>;

	/**
	 * Service Description field in *Services → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter a brief description of the service
	 * - **API ID Path**: services.items[].service_description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	service_description: prismic.RichTextField;

	/**
	 * Feature field in *Services → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter a feature of the service
	 * - **API ID Path**: services.items[].feature
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	feature: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ServicesSliceDefaultPrimary>,
	Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: A slice to showcase Kalvex's services including Management consulting and contracted engineering time
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<'services', ServicesSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			AboutPageDocument,
			AboutPageDocumentData,
			AboutPageDocumentDataSlicesSlice,
			BlogListDocument,
			BlogListDocumentData,
			BlogListDocumentDataSlicesSlice,
			BlogPostDocument,
			BlogPostDocumentData,
			BlogPostDocumentDataSlicesSlice,
			CaseStudiesListDocument,
			CaseStudiesListDocumentData,
			CaseStudiesListDocumentDataSlicesSlice,
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataSlicesSlice,
			ContactsliceDocument,
			ContactsliceDocumentData,
			ContactsliceDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			PrivacyPolicyDocument,
			PrivacyPolicyDocumentData,
			PrivacyPolicyDocumentDataSlicesSlice,
			ServicesDocument,
			ServicesDocumentData,
			ServicesDocumentDataSlicesSlice,
			AllDocumentTypes,
			AboutSlice,
			AboutSliceDefaultPrimary,
			AboutSliceDefaultItem,
			AboutSliceVariation,
			AboutSliceDefault,
			AlternateGridSlice,
			AlternateGridSliceDefaultPrimaryItemsItem,
			AlternateGridSliceDefaultPrimary,
			AlternateGridSliceImageRightPrimaryItemsItem,
			AlternateGridSliceImageRightPrimary,
			AlternateGridSliceVariation,
			AlternateGridSliceDefault,
			AlternateGridSliceImageRight,
			ContactSliceSlice,
			ContactSliceSliceDefaultPrimary,
			ContactSliceSliceVariation,
			ContactSliceSliceDefault,
			LegalPageSlice,
			LegalPageSliceDefaultPrimary,
			LegalPageSliceVariation,
			LegalPageSliceDefault,
			PostcontentSlice,
			PostcontentSliceDefaultPrimary,
			PostcontentSliceVariation,
			PostcontentSliceDefault,
			PostlistSlice,
			PostlistSliceDefaultPrimary,
			PostlistSliceDefaultItem,
			PostlistSliceVariation,
			PostlistSliceDefault,
			ServicesSlice,
			ServicesSliceDefaultPrimary,
			ServicesSliceDefaultItem,
			ServicesSliceVariation,
			ServicesSliceDefault
		};
	}
}
