// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for blog_post_card documents
 */
interface BlogPostCardDocumentData {
	/**
	 * title field in *blog_post_card*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Title
	 * - **API ID Path**: blog_post_card.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * subtitle field in *blog_post_card*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Subtitle
	 * - **API ID Path**: blog_post_card.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * image field in *blog_post_card*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_card.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * blog_post_card document from Prismic
 *
 * - **API ID**: `blog_post_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostCardDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostCardDocumentData>,
	'blog_post_card',
	Lang
>;

type BlogpostDocumentDataSlicesSlice = BlogPostSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
	/**
	 * Slice Zone field in *BlogPost*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
	 * Meta Title field in *BlogPost*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blogpost.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *BlogPost*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blogpost.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *BlogPost*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blogpost.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogpostDocumentData>,
	'blogpost',
	Lang
>;

type CardlistviewDocumentDataSlicesSlice = CardListViewSlice;

/**
 * Content for CardListView documents
 */
interface CardlistviewDocumentData {
	/**
	 * Slice Zone field in *CardListView*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cardlistview.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CardlistviewDocumentDataSlicesSlice> /**
	 * Meta Title field in *CardListView*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: cardlistview.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *CardListView*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: cardlistview.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *CardListView*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cardlistview.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * CardListView document from Prismic
 *
 * - **API ID**: `cardlistview`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardlistviewDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CardlistviewDocumentData>,
	'cardlistview',
	Lang
>;

type HomepageDocumentDataSlicesSlice = AlternateGridSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *HomePage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *HomePage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *HomePage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *HomePage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

export type AllDocumentTypes =
	| BlogPostCardDocument
	| BlogpostDocument
	| CardlistviewDocument
	| HomepageDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
	/**
	 * title field in *AlternateGrid → Default → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Default → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
	/**
	 * title field in *AlternateGrid → Image Right → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Image Right → Primary → items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
	/**
	 * eyebrowHeadline field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrowHeadline: prismic.KeyTextField;

	/**
	 * title field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * image field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * items field in *AlternateGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AlternateGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AlternateGridSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
	/**
	 * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Eyebrow
	 * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrowHeadline: prismic.KeyTextField;

	/**
	 * title field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * description field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * image field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * items field in *AlternateGrid → Image Right → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: alternate_grid.imageRight.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AlternateGridSliceImageRightPrimaryItemsItem>>;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
	'imageRight',
	Simplify<AlternateGridSliceImageRightPrimary>,
	never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation = AlternateGridSliceDefault | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<'alternate_grid', AlternateGridSliceVariation>;

/**
 * Primary content in *BlogPost → Default → Primary*
 */
export interface BlogPostSliceDefaultPrimary {
	/**
	 * Blog Title field in *BlogPost → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter the blog's title here
	 * - **API ID Path**: blog_post.default.primary.blog_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blog_title: prismic.KeyTextField;

	/**
	 * Subheading field in *BlogPost → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Add the subheading of the article
	 * - **API ID Path**: blog_post.default.primary.subheading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subheading: prismic.KeyTextField;

	/**
	 * ArticleImage field in *BlogPost → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.default.primary.articleimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	articleimage: prismic.ImageField<never>;

	/**
	 * PostContent field in *BlogPost → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter your blog content here
	 * - **API ID Path**: blog_post.default.primary.postcontent
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	postcontent: prismic.RichTextField;
}

/**
 * Default variation for BlogPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BlogPostSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BlogPost*
 */
type BlogPostSliceVariation = BlogPostSliceDefault;

/**
 * BlogPost Shared Slice
 *
 * - **API ID**: `blog_post`
 * - **Description**: BlogPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSlice = prismic.SharedSlice<'blog_post', BlogPostSliceVariation>;

/**
 * Primary content in *CardListView → Default → Primary*
 */
export interface CardListViewSliceDefaultPrimary {
	/**
	 * Card List Title field in *CardListView → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: What are the cards showing?
	 * - **API ID Path**: card_list_view.default.primary.card_list_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	card_list_title: prismic.KeyTextField;

	/**
	 * related_content field in *CardListView → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: card_list_view.default.primary.related_content
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	related_content: prismic.ContentRelationshipField<'blogpost'>;
}

/**
 * Default variation for CardListView Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListViewSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardListViewSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CardListView*
 */
type CardListViewSliceVariation = CardListViewSliceDefault;

/**
 * CardListView Shared Slice
 *
 * - **API ID**: `card_list_view`
 * - **Description**: CardListView
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardListViewSlice = prismic.SharedSlice<'card_list_view', CardListViewSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogPostCardDocument,
			BlogPostCardDocumentData,
			BlogpostDocument,
			BlogpostDocumentData,
			BlogpostDocumentDataSlicesSlice,
			CardlistviewDocument,
			CardlistviewDocumentData,
			CardlistviewDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AlternateGridSlice,
			AlternateGridSliceDefaultPrimaryItemsItem,
			AlternateGridSliceDefaultPrimary,
			AlternateGridSliceImageRightPrimaryItemsItem,
			AlternateGridSliceImageRightPrimary,
			AlternateGridSliceVariation,
			AlternateGridSliceDefault,
			AlternateGridSliceImageRight,
			BlogPostSlice,
			BlogPostSliceDefaultPrimary,
			BlogPostSliceVariation,
			BlogPostSliceDefault,
			CardListViewSlice,
			CardListViewSliceDefaultPrimary,
			CardListViewSliceVariation,
			CardListViewSliceDefault
		};
	}
}
